FORMAT: 1A
HOST: http://factory.zone/api/v1/

# Department

## Departments [/company/{company_id}/departments{?page,size}]
+ Parameters
    + company_id(required, number,`1`)
    

### Create Department [POST]

+ Request (application/json)
    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "departmentName" : "Sales"
                "departmentInfo" : "They close the deal, doesn't seem like too much work"
            }    
        
            
            
+ Response 201 (application/json)

    + Headers 
        
            Location: /departments/:id
    
    + Body
    
            {
                "user_id":1
                "company_id":1
                "department_id":1
                "departmentName" : "Sales"
                "departmentInfo" : "They close the deal, doesn't seem like too much work"
                "createdAt" : "2017-6-21 08:12:05"
            }

### List Departments[GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)

    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body
        
            {
                                    
                "page":
                {
                    "number":1,
                    "size":10 
                    "totalPages": 20
                },
                "departments":
                [
                    {
                        "user_id":1
                        "company_id":1
                        "department_id":1
                        "departmentName" : "Design"
                        "departmentInfo" : "They make everything look great and they really shouldn't be with marketing"
                        "createdAt" : "2017-6-21 08:12:05"
                        "updatedAt" : "2017-12-01 13:21:14"
                    },
                    {
                        "user_id":1
                        "company_id":1
                        "department_id":2
                        "departmentName" : "Marketing"
                        "departmentInfo" : "They sell your product, they can sell you a pile of poop"
                        "createdAt" : "2017-6-21 08:12:05"
                        "updatedAt" : "2017-12-01 13:21:14"
                    },
                    {
                        "user_id":2
                        "company_id":1
                        "department_id":3
                        "departmentName" : "Sales"
                        "departmentInfo" : "They close the deal, doesn't seem like too much work"
                        "createdAt" : "2017-6-21 08:12:05"
                        "updatedAt" : "2017-12-01 13:21:14"
                    }
                ]
            }

## Department [/company/{company_id}/departments/{department_id}]
+ Parameters
    + company_id(required, number,`1`)
    + department_id(required, number, `2`)

### Edit Department [PUT]

+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "departmentName" : "Design"
                "departmentInfo" : "They make everything look shiny and they really shouldn't be with marketing"
            }     
        
            
            
+ Response 200 (application/json)

    + Headers 
        
            Location: /departments:id
    
    + Body
    
            {
                "user_id":1
                "company_id":1
                "department_id":1
                "departmentName" : "Design"
                "departmentInfo" : "They make everything look shiny and they really shouldn't be with marketing"
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAT": "2018-02-31 03:20:00"
            }

### View Department [GET]
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
    
            {
                "user_id":2
                "company_id":1
                "department_id":1
                "departmentName" : "Design"
                "departmentInfo" : "They make everything look great and they really shouldn't be with marketing"
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAt" : "2017-12-01 13:21:14"
            }

### Delete Department [DELETE]

+ Response 204